import { nanoid } from "nanoid";
import { IData } from "./surveyData";

//old
// export const initialState = {
//   users: [
//     {
//       name: "Коновалов Илья Александрович",
//       position: "Помощник менеджера по продажам",
//       department: "Направление оптовых продаж",
//       avatar: "https://material-ui.com/static/images/avatar/1.jpg",
//     },
//   ],
//
//   // тип прохождения списков вопросов: линейный или нелинейный
//   questionListTypeLinear: true,
//   // возможность видеть ответы на пройденном листе вопросов
//   questionListViewPreviousPage: true,
//   // возможность редактировать введенные ответы на пройденном листе вопросов
//   questionListEditPreviousPage: true,
//   pages: [
//     {
//       id: nanoid(),
//       name: "Первый список вопросов",
//       progress: 100,
//       allPagesProgress: 70,
//       expanded: true,
//       // timestamp
//       questionsList: [
//         {
//           id: nanoid(),
//           type: "checkbox",
//           question: "Как вы оценивате сотрудника Ивана Николаевича?",
//           // settings: {
//
//           // }
//           questionDone: true,
//           questionRequired: false,
//           comment: false,
//           commentRequired: false,
//           commentValue: null,
//           validationError: false,
//           validationCommentError: false,
//           choices: [
//             {
//               //id: uid
//               //label "вариант1"
//               //value false
//               id: nanoid(),
//               answer: "Положительно",
//               checked: false,
//             },
//             {
//               id: nanoid(),
//               answer: "Нейтрально",
//               checked: false,
//             },
//             {
//               id: nanoid(),
//               answer: "Отрицательно",
//               checked: false,
//             },
//           ],
//           answers: "Положительно",
//         },
//         {
//           id: nanoid(),
//           type: "checkbox",
//           question: "Всегда ли вы достигаете необходимых результатов в работе?",
//           questionDone: true,
//           questionRequired: true,
//           comment: false,
//           commentRequired: false,
//           commentValue: null,
//           validationError: false,
//           validationCommentError: false,
//           choices: [
//             {
//               id: nanoid(),
//               answer: "Всегда",
//               checked: false,
//             },
//             {
//               id: nanoid(),
//               answer: "Иногда",
//               checked: false,
//             },
//             {
//               id: nanoid(),
//               answer: "Редко",
//               checked: false,
//             },
//           ],
//           answers: "Всегда",
//         },
//         {
//           id: nanoid(),
//           type: "radio",
//           question:
//             "Согласны ли вы, что сотрудник дает полезную критику для окружающих?",
//           questionDone: false,
//           questionRequired: true,
//           comment: true,
//           commentRequired: false,
//           commentValue: null,
//           validationError: false,
//           validationCommentError: false,
//           choices: [
//             {
//               id: nanoid(),
//               answer: "Всегда",
//               checked: false,
//             },
//             {
//               id: nanoid(),
//               answer: "Иногда",
//               checked: false,
//             },
//             {
//               id: nanoid(),
//               answer: "Никогда",
//               checked: false,
//             },
//           ],
//           answers: "Иногда",
//         },
//         {
//           id: nanoid(),
//           type: "rating",
//           question:
//             "Оцените умение находить новых клиентов по пятибальной шкале, где 1 это плохо, а 5 это хорошо, установите нужное значение для вашего выбора",
//           questionDone: false,
//           questionRequired: false,
//           comment: true,
//           commentRequired: false,
//           commentValue: null,
//           validationError: false,
//           validationCommentError: false,
//           choices: ["item1", "item2", "item3"],
//           answers: "5",
//         },
//       ],
//     },
//     {
//       id: nanoid(),
//       name: "Второй список вопросов",
//       progress: 45,
//       questionsList: [
//         {
//           id: nanoid(),
//           type: "checkbox",
//           question: "Второй список вопросов Checkbox",
//           questionRequired: true,
//           comment: false,
//           commentRequired: false,
//           commentValue: null,
//           validationError: false,
//           validationCommentError: false,
//           choices: [
//             {
//               id: nanoid(),
//               answer: "вариант1",
//               checked: false,
//             },
//             {
//               id: nanoid(),
//               answer: "вариант2",
//               checked: false,
//             },
//             {
//               id: nanoid(),
//               answer: "вариант3",
//               checked: false,
//             },
//           ],
//           answers: [],
//         },
//         {
//           id: nanoid(),
//           type: "radio",
//           question: "Второй список вопросов Radio",
//           questionRequired: false,
//           comment: true,
//           commentRequired: false,
//           commentValue: null,
//           validationError: false,
//           validationCommentError: false,
//           choices: [
//             {
//               id: nanoid(),
//               answer: "вариант1",
//               checked: false,
//             },
//             {
//               id: nanoid(),
//               answer: "вариант2",
//               checked: false,
//             },
//             {
//               id: nanoid(),
//               answer: "вариант3",
//               checked: false,
//             },
//           ],
//           answers: [],
//         },
//         {
//           id: nanoid(),
//           type: "rating",
//           question: "Второй список вопросов Rating",
//           questionRequired: true,
//           comment: true,
//           commentRequired: false,
//           commentValue: null,
//           validationError: false,
//           validationCommentError: false,
//           choices: ["item1", "item2", "item3"],
//           answers: [],
//         },
//       ],
//     },
//     {
//       id: nanoid(),
//       name: "Третий список вопросов",
//       progress: 65,
//       questionsList: [
//         {
//           id: nanoid(),
//           type: "checkbox",
//           question: "Третий список вопросов Checkbox",
//           questionRequired: true,
//           comment: false,
//           commentRequired: false,
//           commentValue: null,
//           validationError: false,
//           validationCommentError: false,
//           choices: [
//             {
//               id: nanoid(),
//               answer: "вариант1",
//               checked: false,
//             },
//             {
//               id: nanoid(),
//               answer: "вариант2",
//               checked: false,
//             },
//             {
//               id: nanoid(),
//               answer: "вариант3",
//               checked: false,
//             },
//           ],
//           answers: [],
//         },
//         {
//           id: nanoid(),
//           type: "radio",
//           question: "Третий список вопросов Radio",
//           questionRequired: false,
//           comment: true,
//           commentRequired: false,
//           commentValue: null,
//           validationError: false,
//           validationCommentError: false,
//           choices: [
//             {
//               id: nanoid(),
//               answer: "вариант1",
//               checked: false,
//             },
//             {
//               id: nanoid(),
//               answer: "вариант2",
//               checked: false,
//             },
//             {
//               id: nanoid(),
//               answer: "вариант3",
//               checked: false,
//             },
//           ],
//           answers: [],
//         },
//         {
//           id: nanoid(),
//           type: "rating",
//           question: "Третий список вопросов Rating",
//           questionRequired: true,
//           comment: true,
//           commentRequired: false,
//           commentValue: null,
//           validationError: false,
//           validationCommentError: false,
//           choices: ["item1", "item2", "item3"],
//           answers: [],
//         },
//       ],
//     },
//     {
//       id: nanoid(),
//       name: "Четвертый список вопросов",
//       progress: 55,
//       questionsList: [
//         {
//           id: nanoid(),
//           type: "checkbox",
//           question: "Четвертый список вопросов Checkbox",
//           questionRequired: true,
//           comment: false,
//           commentRequired: false,
//           commentValue: null,
//           validationError: false,
//           validationCommentError: false,
//           choices: [
//             {
//               id: nanoid(),
//               answer: "вариант1",
//               checked: false,
//             },
//             {
//               id: nanoid(),
//               answer: "вариант2",
//               checked: false,
//             },
//             {
//               id: nanoid(),
//               answer: "вариант3",
//               checked: false,
//             },
//           ],
//           answers: [],
//         },
//         {
//           id: nanoid(),
//           type: "radio",
//           question: "Четвертый список вопросов Radio",
//           questionRequired: false,
//           comment: true,
//           commentRequired: false,
//           commentValue: null,
//           validationError: false,
//           validationCommentError: false,
//           choices: [
//             {
//               id: nanoid(),
//               answer: "вариант1",
//               checked: false,
//             },
//             {
//               id: nanoid(),
//               answer: "вариант2",
//               checked: false,
//             },
//             {
//               id: nanoid(),
//               answer: "вариант3",
//               checked: false,
//             },
//           ],
//           answers: [],
//         },
//         {
//           id: nanoid(),
//           type: "rating",
//           question: "Четвертый список вопросов Rating",
//           questionRequired: true,
//           comment: true,
//           commentRequired: false,
//           commentValue: null,
//           validationError: false,
//           validationCommentError: false,
//           choices: ["item1", "item2", "item3"],
//           answers: [],
//         },
//       ],
//     },
//     {
//       id: nanoid(),
//       name: "Пятый список вопросов",
//       progress: 0,
//       disabled: true,
//       questionsList: [
//         {
//           id: nanoid(),
//           type: "checkbox",
//           question: "Пятый список вопросов Checkbox",
//           questionRequired: true,
//           comment: false,
//           commentRequired: false,
//           commentValue: null,
//           validationError: false,
//           validationCommentError: false,
//           choices: [
//             {
//               id: nanoid(),
//               answer: "вариант1",
//               checked: false,
//             },
//             {
//               id: nanoid(),
//               answer: "вариант2",
//               checked: false,
//             },
//             {
//               id: nanoid(),
//               answer: "вариант3",
//               checked: false,
//             },
//           ],
//           answers: [],
//         },
//         {
//           id: nanoid(),
//           type: "radio",
//           question: "Пятый список вопросов Radio",
//           questionRequired: false,
//           comment: true,
//           commentRequired: false,
//           commentValue: null,
//           validationError: false,
//           validationCommentError: false,
//           choices: [
//             {
//               id: nanoid(),
//               answer: "вариант1",
//               checked: false,
//             },
//             {
//               id: nanoid(),
//               answer: "вариант2",
//               checked: false,
//             },
//             {
//               id: nanoid(),
//               answer: "вариант3",
//               checked: false,
//             },
//           ],
//           answers: [],
//         },
//         {
//           id: nanoid(),
//           type: "rating",
//           question: "Пятый список вопросов Rating",
//           questionRequired: true,
//           comment: true,
//           commentRequired: false,
//           commentValue: null,
//           validationError: false,
//           validationCommentError: false,
//           choices: ["item1", "item2", "item3"],
//           answers: [],
//         },
//       ],
//     },
//     {
//       id: nanoid(),
//       name: "Шестой список вопросов",
//       progress: 0,
//       disabled: true,
//       questionsList: [
//         {
//           id: nanoid(),
//           type: "checkbox",
//           question: "Шестой список вопросов Checkbox",
//           questionRequired: true,
//           comment: false,
//           commentRequired: false,
//           commentValue: null,
//           validationError: false,
//           validationCommentError: false,
//           choices: [
//             {
//               id: nanoid(),
//               answer: "вариант1",
//               checked: false,
//             },
//             {
//               id: nanoid(),
//               answer: "вариант2",
//               checked: false,
//             },
//             {
//               id: nanoid(),
//               answer: "вариант3",
//               checked: false,
//             },
//           ],
//           answers: [],
//         },
//         {
//           id: nanoid(),
//           type: "radio",
//           question: "Шестой список вопросов Radio",
//           questionRequired: false,
//           comment: true,
//           commentRequired: false,
//           commentValue: null,
//           validationError: false,
//           validationCommentError: false,
//           choices: [
//             {
//               id: nanoid(),
//               answer: "вариант1",
//               checked: false,
//             },
//             {
//               id: nanoid(),
//               answer: "вариант2",
//               checked: false,
//             },
//             {
//               id: nanoid(),
//               answer: "вариант3",
//               checked: false,
//             },
//           ],
//           answers: [],
//         },
//         {
//           id: nanoid(),
//           type: "rating",
//           question: "Шестой список вопросов Rating",
//           questionRequired: true,
//           comment: true,
//           commentRequired: false,
//           commentValue: null,
//           validationError: false,
//           validationCommentError: false,
//           choices: ["item1", "item2", "item3"],
//           answers: [],
//         },
//       ],
//     },
//     {
//       id: nanoid(),
//       name: "Седьмой список вопросов",
//       progress: 0,
//       disabled: true,
//       questionsList: [
//         {
//           id: nanoid(),
//           type: "checkbox",
//           question: "Седьмой список вопросов Checkbox",
//           questionRequired: true,
//           comment: false,
//           commentRequired: false,
//           commentValue: null,
//           validationError: false,
//           validationCommentError: false,
//           choices: [
//             {
//               id: nanoid(),
//               answer: "вариант1",
//               checked: false,
//             },
//             {
//               id: nanoid(),
//               answer: "вариант2",
//               checked: false,
//             },
//             {
//               id: nanoid(),
//               answer: "вариант3",
//               checked: false,
//             },
//           ],
//           answers: [],
//         },
//         {
//           id: nanoid(),
//           type: "radio",
//           question: "Седьмой список вопросов Radio",
//           questionRequired: false,
//           comment: true,
//           commentRequired: false,
//           commentValue: null,
//           validationError: false,
//           validationCommentError: false,
//           choices: [
//             {
//               id: nanoid(),
//               answer: "вариант1",
//               checked: false,
//             },
//             {
//               id: nanoid(),
//               answer: "вариант2",
//               checked: false,
//             },
//             {
//               id: nanoid(),
//               answer: "вариант3",
//               checked: false,
//             },
//           ],
//           answers: [],
//         },
//         {
//           id: nanoid(),
//           type: "rating",
//           question: "Седьмой список вопросов Rating",
//           questionRequired: true,
//           comment: true,
//           commentRequired: false,
//           commentValue: null,
//           validationError: false,
//           validationCommentError: false,
//           choices: ["item1", "item2", "item3"],
//           answers: [],
//         },
//       ],
//     },
//   ],
// };

// export const initialState = {
//   users: [
//     {
//       name: "Коновалов Илья Александрович",
//       position: "Помощник менеджера по продажам",
//       department: "Направление оптовых продаж",
//       avatar: "https://material-ui.com/static/images/avatar/1.jpg",
//     },
//   ],
//
//   // тип прохождения списков вопросов: линейный или нелинейный
//   questionListTypeLinear: true,
//   // возможность видеть ответы на пройденном листе вопросов
//   questionListViewPreviousPage: true,
//   // возможность редактировать введенные ответы на пройденном листе вопросов
//   questionListEditPreviousPage: true,
//   pages: [
//     {
//       id: nanoid(),
//       name: "Первый список вопросов",
//       progress: 100,
//       allPagesProgress: 70,
//       expanded: true,
//       // timestamp
//       questionsList: [
//         {
//           id: nanoid(),
//           type: "checkbox",
//           question: "Как вы оценивате сотрудника Ивана Николаевича?",
//           // settings: {
//
//           // }
//           questionDone: true,
//           questionRequired: false,
//           comment: false,
//           commentRequired: false,
//           commentValue: null,
//           validationError: false,
//           validationCommentError: false,
//           choices: [
//             {
//               //id: uid
//               //label "вариант1"
//               //value false
//               id: nanoid(),
//               answer: "Положительно",
//               checked: false,
//             },
//             {
//               id: nanoid(),
//               answer: "Нейтрально",
//               checked: false,
//             },
//             {
//               id: nanoid(),
//               answer: "Отрицательно",
//               checked: false,
//             },
//           ],
//           answers: "Положительно",
//         },
//         {
//           id: nanoid(),
//           type: "checkbox",
//           question: "Всегда ли вы достигаете необходимых результатов в работе?",
//           questionDone: true,
//           questionRequired: true,
//           comment: false,
//           commentRequired: false,
//           commentValue: null,
//           validationError: false,
//           validationCommentError: false,
//           choices: [
//             {
//               id: nanoid(),
//               answer: "Всегда",
//               checked: false,
//             },
//             {
//               id: nanoid(),
//               answer: "Иногда",
//               checked: false,
//             },
//             {
//               id: nanoid(),
//               answer: "Редко",
//               checked: false,
//             },
//           ],
//           answers: "Всегда",
//         },
//         {
//           id: nanoid(),
//           type: "radio",
//           question:
//             "Согласны ли вы, что сотрудник дает полезную критику для окружающих?",
//           questionDone: false,
//           questionRequired: true,
//           comment: true,
//           commentRequired: false,
//           commentValue: null,
//           validationError: false,
//           validationCommentError: false,
//           choices: [
//             {
//               id: nanoid(),
//               answer: "Всегда",
//               checked: false,
//             },
//             {
//               id: nanoid(),
//               answer: "Иногда",
//               checked: false,
//             },
//             {
//               id: nanoid(),
//               answer: "Никогда",
//               checked: false,
//             },
//           ],
//           answers: "Иногда",
//         },
//         {
//           id: nanoid(),
//           type: "rating",
//           question:
//             "Оцените умение находить новых клиентов по пятибальной шкале, где 1 это плохо, а 5 это хорошо, установите нужное значение для вашего выбора",
//           questionDone: false,
//           questionRequired: false,
//           comment: true,
//           commentRequired: false,
//           commentValue: null,
//           validationError: false,
//           validationCommentError: false,
//           choices: ["item1", "item2", "item3"],
//           answers: "5",
//         },
//       ],
//     },
//     {
//       id: nanoid(),
//       name: "Второй список вопросов",
//       progress: 45,
//       questionsList: [
//         {
//           id: nanoid(),
//           type: "checkbox",
//           question: "Второй список вопросов Checkbox",
//           questionRequired: true,
//           comment: false,
//           commentRequired: false,
//           commentValue: null,
//           validationError: false,
//           validationCommentError: false,
//           choices: [
//             {
//               id: nanoid(),
//               answer: "вариант1",
//               checked: false,
//             },
//             {
//               id: nanoid(),
//               answer: "вариант2",
//               checked: false,
//             },
//             {
//               id: nanoid(),
//               answer: "вариант3",
//               checked: false,
//             },
//           ],
//           answers: [],
//         },
//         {
//           id: nanoid(),
//           type: "radio",
//           question: "Второй список вопросов Radio",
//           questionRequired: false,
//           comment: true,
//           commentRequired: false,
//           commentValue: null,
//           validationError: false,
//           validationCommentError: false,
//           choices: [
//             {
//               id: nanoid(),
//               answer: "вариант1",
//               checked: false,
//             },
//             {
//               id: nanoid(),
//               answer: "вариант2",
//               checked: false,
//             },
//             {
//               id: nanoid(),
//               answer: "вариант3",
//               checked: false,
//             },
//           ],
//           answers: [],
//         },
//         {
//           id: nanoid(),
//           type: "rating",
//           question: "Второй список вопросов Rating",
//           questionRequired: true,
//           comment: true,
//           commentRequired: false,
//           commentValue: null,
//           validationError: false,
//           validationCommentError: false,
//           choices: ["item1", "item2", "item3"],
//           answers: [],
//         },
//       ],
//     },
//     {
//       id: nanoid(),
//       name: "Третий список вопросов",
//       progress: 65,
//       questionsList: [
//         {
//           id: nanoid(),
//           type: "checkbox",
//           question: "Третий список вопросов Checkbox",
//           questionRequired: true,
//           comment: false,
//           commentRequired: false,
//           commentValue: null,
//           validationError: false,
//           validationCommentError: false,
//           choices: [
//             {
//               id: nanoid(),
//               answer: "вариант1",
//               checked: false,
//             },
//             {
//               id: nanoid(),
//               answer: "вариант2",
//               checked: false,
//             },
//             {
//               id: nanoid(),
//               answer: "вариант3",
//               checked: false,
//             },
//           ],
//           answers: [],
//         },
//         {
//           id: nanoid(),
//           type: "radio",
//           question: "Третий список вопросов Radio",
//           questionRequired: false,
//           comment: true,
//           commentRequired: false,
//           commentValue: null,
//           validationError: false,
//           validationCommentError: false,
//           choices: [
//             {
//               id: nanoid(),
//               answer: "вариант1",
//               checked: false,
//             },
//             {
//               id: nanoid(),
//               answer: "вариант2",
//               checked: false,
//             },
//             {
//               id: nanoid(),
//               answer: "вариант3",
//               checked: false,
//             },
//           ],
//           answers: [],
//         },
//         {
//           id: nanoid(),
//           type: "rating",
//           question: "Третий список вопросов Rating",
//           questionRequired: true,
//           comment: true,
//           commentRequired: false,
//           commentValue: null,
//           validationError: false,
//           validationCommentError: false,
//           choices: ["item1", "item2", "item3"],
//           answers: [],
//         },
//       ],
//     },
//     {
//       id: nanoid(),
//       name: "Четвертый список вопросов",
//       progress: 55,
//       questionsList: [
//         {
//           id: nanoid(),
//           type: "checkbox",
//           question: "Четвертый список вопросов Checkbox",
//           questionRequired: true,
//           comment: false,
//           commentRequired: false,
//           commentValue: null,
//           validationError: false,
//           validationCommentError: false,
//           choices: [
//             {
//               id: nanoid(),
//               answer: "вариант1",
//               checked: false,
//             },
//             {
//               id: nanoid(),
//               answer: "вариант2",
//               checked: false,
//             },
//             {
//               id: nanoid(),
//               answer: "вариант3",
//               checked: false,
//             },
//           ],
//           answers: [],
//         },
//         {
//           id: nanoid(),
//           type: "radio",
//           question: "Четвертый список вопросов Radio",
//           questionRequired: false,
//           comment: true,
//           commentRequired: false,
//           commentValue: null,
//           validationError: false,
//           validationCommentError: false,
//           choices: [
//             {
//               id: nanoid(),
//               answer: "вариант1",
//               checked: false,
//             },
//             {
//               id: nanoid(),
//               answer: "вариант2",
//               checked: false,
//             },
//             {
//               id: nanoid(),
//               answer: "вариант3",
//               checked: false,
//             },
//           ],
//           answers: [],
//         },
//         {
//           id: nanoid(),
//           type: "rating",
//           question: "Четвертый список вопросов Rating",
//           questionRequired: true,
//           comment: true,
//           commentRequired: false,
//           commentValue: null,
//           validationError: false,
//           validationCommentError: false,
//           choices: ["item1", "item2", "item3"],
//           answers: [],
//         },
//       ],
//     },
//     {
//       id: nanoid(),
//       name: "Пятый список вопросов",
//       progress: 0,
//       disabled: true,
//       questionsList: [
//         {
//           id: nanoid(),
//           type: "checkbox",
//           question: "Пятый список вопросов Checkbox",
//           questionRequired: true,
//           comment: false,
//           commentRequired: false,
//           commentValue: null,
//           validationError: false,
//           validationCommentError: false,
//           choices: [
//             {
//               id: nanoid(),
//               answer: "вариант1",
//               checked: false,
//             },
//             {
//               id: nanoid(),
//               answer: "вариант2",
//               checked: false,
//             },
//             {
//               id: nanoid(),
//               answer: "вариант3",
//               checked: false,
//             },
//           ],
//           answers: [],
//         },
//         {
//           id: nanoid(),
//           type: "radio",
//           question: "Пятый список вопросов Radio",
//           questionRequired: false,
//           comment: true,
//           commentRequired: false,
//           commentValue: null,
//           validationError: false,
//           validationCommentError: false,
//           choices: [
//             {
//               id: nanoid(),
//               answer: "вариант1",
//               checked: false,
//             },
//             {
//               id: nanoid(),
//               answer: "вариант2",
//               checked: false,
//             },
//             {
//               id: nanoid(),
//               answer: "вариант3",
//               checked: false,
//             },
//           ],
//           answers: [],
//         },
//         {
//           id: nanoid(),
//           type: "rating",
//           question: "Пятый список вопросов Rating",
//           questionRequired: true,
//           comment: true,
//           commentRequired: false,
//           commentValue: null,
//           validationError: false,
//           validationCommentError: false,
//           choices: ["item1", "item2", "item3"],
//           answers: [],
//         },
//       ],
//     },
//     {
//       id: nanoid(),
//       name: "Шестой список вопросов",
//       progress: 0,
//       disabled: true,
//       questionsList: [
//         {
//           id: nanoid(),
//           type: "checkbox",
//           question: "Шестой список вопросов Checkbox",
//           questionRequired: true,
//           comment: false,
//           commentRequired: false,
//           commentValue: null,
//           validationError: false,
//           validationCommentError: false,
//           choices: [
//             {
//               id: nanoid(),
//               answer: "вариант1",
//               checked: false,
//             },
//             {
//               id: nanoid(),
//               answer: "вариант2",
//               checked: false,
//             },
//             {
//               id: nanoid(),
//               answer: "вариант3",
//               checked: false,
//             },
//           ],
//           answers: [],
//         },
//         {
//           id: nanoid(),
//           type: "radio",
//           question: "Шестой список вопросов Radio",
//           questionRequired: false,
//           comment: true,
//           commentRequired: false,
//           commentValue: null,
//           validationError: false,
//           validationCommentError: false,
//           choices: [
//             {
//               id: nanoid(),
//               answer: "вариант1",
//               checked: false,
//             },
//             {
//               id: nanoid(),
//               answer: "вариант2",
//               checked: false,
//             },
//             {
//               id: nanoid(),
//               answer: "вариант3",
//               checked: false,
//             },
//           ],
//           answers: [],
//         },
//         {
//           id: nanoid(),
//           type: "rating",
//           question: "Шестой список вопросов Rating",
//           questionRequired: true,
//           comment: true,
//           commentRequired: false,
//           commentValue: null,
//           validationError: false,
//           validationCommentError: false,
//           choices: ["item1", "item2", "item3"],
//           answers: [],
//         },
//       ],
//     },
//     {
//       id: nanoid(),
//       name: "Седьмой список вопросов",
//       progress: 0,
//       disabled: true,
//       questionsList: [
//         {
//           id: nanoid(),
//           type: "checkbox",
//           question: "Седьмой список вопросов Checkbox",
//           questionRequired: true,
//           comment: false,
//           commentRequired: false,
//           commentValue: null,
//           validationError: false,
//           validationCommentError: false,
//           choices: [
//             {
//               id: nanoid(),
//               answer: "вариант1",
//               checked: false,
//             },
//             {
//               id: nanoid(),
//               answer: "вариант2",
//               checked: false,
//             },
//             {
//               id: nanoid(),
//               answer: "вариант3",
//               checked: false,
//             },
//           ],
//           answers: [],
//         },
//         {
//           id: nanoid(),
//           type: "radio",
//           question: "Седьмой список вопросов Radio",
//           questionRequired: false,
//           comment: true,
//           commentRequired: false,
//           commentValue: null,
//           validationError: false,
//           validationCommentError: false,
//           choices: [
//             {
//               id: nanoid(),
//               answer: "вариант1",
//               checked: false,
//             },
//             {
//               id: nanoid(),
//               answer: "вариант2",
//               checked: false,
//             },
//             {
//               id: nanoid(),
//               answer: "вариант3",
//               checked: false,
//             },
//           ],
//           answers: [],
//         },
//         {
//           id: nanoid(),
//           type: "rating",
//           question: "Седьмой список вопросов Rating",
//           questionRequired: true,
//           comment: true,
//           commentRequired: false,
//           commentValue: null,
//           validationError: false,
//           validationCommentError: false,
//           choices: ["item1", "item2", "item3"],
//           answers: [],
//         },
//       ],
//     },
//   ],
// };

export const initialState: IData = {
  users: [
    {
      name: "Коновалов Илья Александрович",
      position: "Помощник менеджера по продажам",
      department: "Направление оптовых продаж",
      avatar: "https://material-ui.com/static/images/avatar/1.jpg",
    },
  ],
  surveyCampanings: [
    {
      id: "FP74P1GERMQF78",
      name: "Тест только текст",
      startDate: "08.09.2022",
      endDate: "08.09.2022",
      surveyType: "linear",
      reviewStrict: true,
      editingStrict: true,
      campaningIsDone: false,
      sections: [
        {
          id: "FP74P1GERMQF78_1",
          name: "секция 1 тест",
          disabled: false,
          progress: 0,
          allSectionsProgress: 0,
          expanded: true,
          isActive: true,
          questions: [
            {
              id: "FP74P1GERMQF78_1_FP74P1GERPUMNH",
              type: "radio",
              questionText: "Вопрос радио перечисление",
              questionDone: false,
              questionRequired: true,
              comment: false,
              commentRequired: false,
              commentValue: "",
              validationError: false,
              validationCommentError: false,
              isActive: true,
              choices: [
                {
                  id: "Да",
                  answerText: "Да",
                  checked: false,
                },
                {
                  id: "Нет",
                  answerText: "Нет",
                  checked: false,
                },
              ],
              userAnswer: [],
              rules: [],
            },
          ],
        },
        {
          id: "FP74P1GERMQF78_2",
          name: "секция 2 тест будет первым",
          disabled: false,
          progress: 0,
          allSectionsProgress: 0,
          expanded: true,
          isActive: true,
          questions: [
            {
              id: "FP74P1GERMQF78_2_FP74P1GERPGEFF",
              type: "radio",
              questionText: "Радио справочник",
              questionDone: false,
              questionRequired: false,
              comment: false,
              commentRequired: false,
              commentValue: "",
              validationError: false,
              validationCommentError: false,
              isActive: true,
              choices: [
                {
                  id: "{SurveyData.Справочники.запОтветы:1}",
                  answerText: "Ответ 1",
                  checked: false,
                },
                {
                  id: "{SurveyData.Справочники.запОтветы:2}",
                  answerText: "Ответ 2",
                  checked: false,
                },
              ],
              userAnswer: [],
              rules: [],
            },
            {
              id: "FP74P1GERMQF78_2_FP74P1GGANRKUA",
              type: "checkbox",
              questionText: "чекбокс перечисление",
              questionDone: false,
              questionRequired: false,
              comment: false,
              commentRequired: false,
              commentValue: "",
              validationError: false,
              validationCommentError: false,
              isActive: true,
              choices: [
                {
                  id: "Я",
                  answerText: "Я",
                  checked: false,
                },
                {
                  id: "Ты",
                  answerText: "Ты",
                  checked: false,
                },
                {
                  id: "Он",
                  answerText: "Он",
                  checked: false,
                },
                {
                  id: "Она",
                  answerText: "Она",
                  checked: false,
                },
              ],
              userAnswer: [],
              rules: [],
            },
            {
              id: "FP74P1GERMQF78_2_FP74P1GGASAIUB",
              type: "checkbox",
              questionText: "Чекбокс из справочника",
              questionDone: false,
              questionRequired: false,
              comment: false,
              commentRequired: false,
              commentValue: "",
              validationError: false,
              validationCommentError: false,
              isActive: true,
              choices: [
                {
                  id: "{SurveyData.Справочники.запОтветы:1}",
                  answerText: "Ответ 1",
                  checked: false,
                },
                {
                  id: "{SurveyData.Справочники.запОтветы:2}",
                  answerText: "Ответ 2",
                  checked: false,
                },
                {
                  id: "{SurveyData.Справочники.запОтветы:3}",
                  answerText: "Вариант 1",
                  checked: false,
                },
                {
                  id: "{SurveyData.Справочники.запОтветы:5}",
                  answerText: "Вариант 2",
                  checked: false,
                },
                {
                  id: "{SurveyData.Справочники.запОтветы:6}",
                  answerText: "Вариант 3",
                  checked: false,
                },
              ],
              userAnswer: [],
              rules: [],
            },
            {
              id: "FP74P1GERMQF78_2_FP74P1GGAT656D",
              type: "textQuestion",
              questionText: "секция 2, вопрос 1",
              questionDone: false,
              questionRequired: false,
              comment: false,
              commentRequired: false,
              commentValue: "",
              validationError: false,
              validationCommentError: false,
              isActive: true,
              choices: null,
              userAnswer: [],
              rules: [],
            },
          ],
        },
      ],
    },
  ],
};
