export const SET_NEW_STATE = "SET_NEW_STATE";
export const CHANGE_CURRENT_PAGE = "CHANGE_CURRENT_PAGE";
export const CHANGE_SLIDE_MOVE_DIRECTION = "CHANGE_SLIDE_MOVE_DIRECTION";
export const SET_CURRENT_SURVEY_CAMPANING_INDEX =
  "SET_CURRENT_SURVEY_CAMPANING_INDEX";
export const SET_CURRENT_SECTION_INDEX = "SET_CURRENT_SECTION_INDEX";
export const SET_CURRENT_QUESTION_INDEX = "SET_CURRENT_QUESTION_INDEX";
export const SET_USER_ANSWER = "SET_USER_ANSWER";
export const SHUFFLE_QUESTIONS_LIST = "SHUFFLE_QUESTIONS_LIST";
export const SET_USER_COMMENT = "SET_USER_COMMENT";
export const RULE_EXECUTION = "RULE_EXECUTION";
export const SET_ERROR = "SET_ERROR";
