export const DEFAULT_CURRENT_USER_INDEX = 0;
export const DEFAULT_CURRENT_QUESTION_INDEX = 0;
export const DEFAULT_CURRENT_PAGE = "main";
export const DEFAULT_MOVE_DIRECTION = "left-to-right";
export const DEFAULT_CURRENT_SURVEY_COMPANING_INDEX = 0;
export const DEFAULT_CURRENT_SECTION_INDEX = 0;
export const TIMEOUT_VALUE = 500;
export const DEFAULT_PAGE_QUESTION_COUNT = 2;
